accounts/urls.py
from django.urls import path
from .import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

inven/urls.py
from . import views
from django.urls import path

app_name = 'inventory'

urlpatterns = [
    path('add/', views.add, name='addProduct',), 
    path('add/json_call/<str:isi>/', views.ajax_call),
]

invenstory/urls.py
from . import views
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('inventory/', include('inven.urls')),
    path('productlist/', include('productlist.urls')),
    path('myinventory/', include('myinventory.urls')),
    path('', views.landing, name='landing'),
    path('sold/', include('terjual.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += staticfiles_urlpatterns()

myinventory/urls.py
from django.urls import path
from . import views

app_name = 'myinventory'

urlpatterns = [
    path('', views.inventory, name='inventory'),
    path('<int:id>/', views.inventory, name='inventory'),
    path('ajax_call/', views.ajax_call),
]

productlist/urls.py
from django.urls import path
from . import views

app_name = 'productlist'

urlpatterns = [
    path('productlist', views.productlist, name='productlist'),
    path('ajax_call/', views.ajax_call),
    ]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    {% block style %}{% endblock %}
    <title>Invenstory </title>

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="{% url 'myinventory:inventory' %}">INVENSTORY</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'inventory:addProduct' %}">ADD</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/sold">SOLD</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'productlist:productlist' %}">LIST</a>
                </li>
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a href="{% url 'accounts:logout' %}" class="nav-link">logout</a>
                    {% else %}
                    <a href="{% url 'accounts:login' %}" class="nav-link">login</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'accounts:signup' %}" class="nav-link">signup</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    {% block script %}{% endblock %}
</body>

</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
<!-- ISIIN YAAA WKWKWK -->
HUAHAHAHAHAH
{% endblock %}